name: morl-dilemmas
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.13
  - numpy>=2.0
  - pandas>=2.2
  - matplotlib>=3.8
  - seaborn>=0.13
  - psutil>=5.9
  - pip
  - pip:
      - dataframe_image>=0.2
      - pympler>=1.0
      - torch==2.11.0
