[tool.poetry]
name = "morl-dilemmas"
version = "0.1.0"
description = "Code for a bachelor's thesis on incorporating moral choices in social dilemmas with multi-objective reinforcement learning."
authors = ["Wilder Rodrigues"]
license = "MIT"
readme = "README.md"
packages = [{ include = "uu", from = "src" }]

[tool.poetry.dependencies]
python = "<3.15,>=3.10"
numpy = ">=2.0"
pandas = ">=2.2"
matplotlib = ">=3.8"
seaborn = ">=0.13"
psutil = ">=5.9"
typer = ">=0.12"
dataframe-image = ">=0.2"
pympler = ">=1.0"
torch = "2.11.0"

[tool.poetry.group.dev.dependencies]
pytest = "*"

[build-system]
requires = ["poetry-core>=1.9.0"]
build-backend = "poetry.core.masonry.api"
